package com.dm.ycm.model.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dm.ycm.model.entity.MentionEntity;

import com.dm.ycm.model.dao.MentionEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mentionEntityDaoConfig;

    private final MentionEntityDao mentionEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mentionEntityDaoConfig = daoConfigMap.get(MentionEntityDao.class).clone();
        mentionEntityDaoConfig.initIdentityScope(type);

        mentionEntityDao = new MentionEntityDao(mentionEntityDaoConfig, this);

        registerDao(MentionEntity.class, mentionEntityDao);
    }
    
    public void clear() {
        mentionEntityDaoConfig.clearIdentityScope();
    }

    public MentionEntityDao getMentionEntityDao() {
        return mentionEntityDao;
    }

}
